version: 0.2

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip terraform_1.7.5_linux_amd64.zip
      - mv terraform /usr/local/bin/

  build:
    commands:
      - rm -rf .terraform
      -terraform fmt
      - terraform init -reconfigure
      - terraform validate
      - terraform plan
      - terraform apply -auto-approve
